[package]
name = "kafka-sniffer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pcap = "0.10.1"
go-flag = "0.1.0"
futures = "0.3"
pcap-sys = "0.1.3"
anyhow = "1.0"
libc = "0.2"